spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/akrdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: changeitpls
    driver-class-name: com.mysql.jdbc.Driver
project:
  name: akr-web-project
  profile: dev