version: "3"

services:
  akr-web-app:
    image: medhanie/akr-web-app
    networks:
      - akr-web-network
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: mysql
    networks:
      - akr-web-network
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=changeitpls
      - MYSQL_DATABASE=erient
    volumes:
      - /Users/medhanie/db/mysql:/var/lib/mysql

networks: akr-web-network:
